# AquariOS system requirements

## Memory

Storage space >200 kilobytes (lite) >1100 kilobytes (full)

## CPU

Clock speed >16khz (lite) >24khz (full)
Minimum clock speed: 16 khz
Overclock starts at: 1 mhz
Max overclock: 1 thz

## Main screen

Resolution 50x50 (minimum) 2160x2160 (maximum)
Refresh rate: 4hz (minimum) 480hz (maximum)

## Operating system

Type = Embedded
Core = TinyOS
Kernel = TinyOS

## Compatible motherboard architectures

FVGA
FPGVGA
????

## PH checking

Currently unknown

## Temperature checking

Currently unknown

## Light sensors

Currently unknown

## Digital wallpaper

### Screen

Currently unknown

### Projector

Currently unknown

## Other components

Currently unknown on:

- PH checking
- Temperature checking
- Light sensors
- Digital wallpaper (screen or projector)

## Blueprint file info

File type: API BluePrint source file (*.apib)
File version: 1 (2022, Monday, March 28th at 1:23 am PST)
Line count (including blank lines and compiler line): 68
File language: English (US)
